---
development:
  cloud_name: cmp-batam
  api_key: '458949694437461'
  api_secret: h1qTkYd4DqCD-iCk6mogG1J4A6Y
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: cmp-batam
  api_key: '458949694437461'
  api_secret: h1qTkYd4DqCD-iCk6mogG1J4A6Y
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: cmp-batam
  api_key: '458949694437461'
  api_secret: h1qTkYd4DqCD-iCk6mogG1J4A6Y
  enhance_image_tag: true
  static_image_support: false
