---
development:
  cloud_name: medioxtra
  api_key: '393825632941392'
  api_secret: fM7sPtVCzPBViFO4DmSkq3Hh8ew
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: medioxtra
  api_key: '393825632941392'
  api_secret: fM7sPtVCzPBViFO4DmSkq3Hh8ew
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: medioxtra
  api_key: '393825632941392'
  api_secret: fM7sPtVCzPBViFO4DmSkq3Hh8ew
  enhance_image_tag: true
  static_image_support: false
